language: php

php:
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpinsights --no-interaction --min-quality=95 --min-complexity=95 --min-architecture=95 --min-style=95
  - vendor/bin/phpunit --coverage-clover=coverage.xml
